### ISSUE TITLE
Document that /usr/bin/env no longer gets environment variables from the container

### ISSUE THREAD

**Issue by deviantintegral** [home-assistant/docker-base#183] opened 2022-07-06 12:14 UTC
I believe I've found an undocumented change from #166 .

Over at https://github.com/pbkhrv/rtl_433-hass-addons/blame/a698bb7e676f8c46fc147cd257ba22f6f9495861/rtl_433/run.sh#L1 we've been using `#!/usr/bin/env bashio` in our run scripts since the project was started. In rebuilding containers, those scripts now fail because none of the environment variables (like `SUPERVISOR_TOKEN`) are passed through. Switching to `#!/usr/bin/with-contenv` fixes this.

I haven't found exactly why this changed, other than running `git bisect` and confirming that the merge from #166 is the first bad commit.

It would be good if this could be documented somewhere as it's pretty tricky to track down.

**Comment by frenck** [comment] 2022-07-06 12:49
> Switching to #!/usr/bin/with-contenv fixes this.

It should have always been that. Please consult the S6-Overlay documentation for more information about using the S6 Overlay.

<https://github.com/just-containers/s6-overlay#readme>

This is not a bug or recent change, therefore closing this issue.

../Frenck

**Closed by frenck** 2022-07-06 12:49 UTC
